<!DOCTYPE html>
<!--
         __         __         __
 .~~~~~.|  |_      |__|.~~~~~.|  |~~.~~~~~.
 |__ ~~||   _|__   |  ||  _  ||     |     |
 |_____||____|__|  |  ||_____||__|__|__|__|
                  |___|
                  st.john.johnson@gmail.com
-->
<html lang="en">
  <head>
    <title>Scrabbler &raquo; {title}</title>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <link rel="canonical" href="http://www.scrabbler.com/" />
    <link rel="shortcut icon" href="favicon.ico" type="image/vnd.microsoft.icon" />
    <link rel="icon" href="favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.3.0/build/cssreset/reset-min.css" />
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.3.0/build/cssbase/base-min.css" />
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.3.0/build/cssfonts/fonts-min.css" />
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.3.0/build/cssgrids/grids-min.css" />
    <link rel="stylesheet" href="css/base.css" type="text/css" media="screen" />
    <script type="text/javascript">
      // HTML 5 - Fix
      document.createElement('nav');
      document.createElement('section');
      document.createElement('footer');
    </script>
  </head>
  <body>
    {body}
  </body>
</html>